name: Build and Release

on:
  push:
    branches: [main, master]
    tags: ['v*']
  pull_request:
    branches: [main, master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target universal-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Verify icon files exist (Unix)
        if: runner.os != 'Windows'
        run: |
          echo "Checking for icon files..."
          ls -la src-tauri/icons/
          echo "32x32.png exists:" $(test -f src-tauri/icons/32x32.png && echo "YES" || echo "NO")
          echo "128x128.png exists:" $(test -f src-tauri/icons/128x128.png && echo "YES" || echo "NO")
          echo "icon.icns exists:" $(test -f src-tauri/icons/icon.icns && echo "YES" || echo "NO")
          echo "icon.ico exists:" $(test -f src-tauri/icons/icon.ico && echo "YES" || echo "NO")

      - name: Verify icon files exist (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "Checking for icon files..."
          Get-ChildItem -Path "src-tauri/icons/" -Name
          echo "32x32.png exists:" $(if (Test-Path "src-tauri/icons/32x32.png") { "YES" } else { "NO" })
          echo "128x128.png exists:" $(if (Test-Path "src-tauri/icons/128x128.png") { "YES" } else { "NO" })
          echo "icon.icns exists:" $(if (Test-Path "src-tauri/icons/icon.icns") { "YES" } else { "NO" })
          echo "icon.ico exists:" $(if (Test-Path "src-tauri/icons/icon.ico") { "YES" } else { "NO" })
        shell: pwsh

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
          releaseName: 'MCP Server Configuration App v__VERSION__'
          releaseBody: |
            ## 🚀 MCP Server Configuration App Release
            
            A desktop application for managing MCP (Model Context Protocol) server configurations for Claude Code users.
            
            ### 📦 Downloads
            - **Windows**: Download the `.msi` installer
            - **macOS**: Download the `.dmg` file (Universal Binary - supports both Intel and Apple Silicon)
            - **Linux**: Download the `.AppImage` or `.deb` package
            
            ### ✨ Key Features
            - Modern UI with DaisyUI components and responsive design
            - Dual editing modes: Form Editor and JSON Editor
            - Real-time configuration validation
            - Server library management with saved configurations
            - Toast notifications for better user experience
            
            ### 🛠️ Technical Details
            - Built with Tauri + TypeScript + Rust
            - Cross-platform compatibility
            - Native file dialogs and system integration
            
            ---
            🤖 **Developed with Claude Code** | 🌍 [Documentation](https://github.com/${{ github.repository }})
          releaseDraft: ${{ github.ref_type != 'tag' }}
          prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'rc') }}
          args: ${{ matrix.args }}

  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript check
        run: npm run build

      - name: Run linting (if available)
        run: npm run lint || echo "No lint script found"
        continue-on-error: true

      - name: Run tests (if available)
        run: npm test || echo "No test script found"
        continue-on-error: true